### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by Ixyk-Wolf** [ssantoshp/zeplyn#1]
I've installed but no matter what there is no zeplyn executable. Searched my entire python directory and nothing. How do you fix this?

**Comment by santoshlite** [comment]
Hey,

Seems strange, can you show me an example of what it gives you when it's not "executable"?

Try to go to the directory where you pip installed zeplyn with the command prompt and then run ```zeplyn``` in the command prompt.
Does it show you something?

**Comment by Ixyk-Wolf** [comment]
Here is what it says if I try and run it. "'zeplyn' is not recognized as an internal or external command,
operable program or batch file.". I haven't tried it on my linux machine, but it shouldn't make a difference. It also didn't give me a script location not on path warning.

**Comment by santoshlite** [comment]
You pip installed it in the correct directory, right?

Can you tell me how did you do it from start, please?

**Comment by Ixyk-Wolf** [comment]
Here is me installing it on wsl2:
--LOG--
pip install zeplyn
Defaulting to user installation because normal site-packages is not writeable
Collecting zeplyn
  Downloading zeplyn-0.1.0-py3-none-any.whl (2.2 kB)
Collecting twine
  Downloading twine-3.4.1-py3-none-any.whl (34 kB)
Requirement already satisfied: keyring>=15.1 in /usr/lib/python3/dist-packages (from twine->zeplyn) (18.0.1)
Collecting importlib-metadata>=3.6
  Downloading importlib_metadata-4.5.0-py3-none-any.whl (17 kB)
Collecting rfc3986>=1.4.0
  Downloading rfc3986-1.5.0-py2.py3-none-any.whl (31 kB)
Requirement already satisfied: requests>=2.20 in /usr/lib/python3/dist-packages (from twine->zeplyn) (2.22.0)
Collecting tqdm>=4.14
  Downloading tqdm-4.61.0-py2.py3-none-any.whl (75 kB)
     |████████████████████████████████| 75 kB 5.6 MB/s
Collecting readme-renderer>=21.0
  Downloading readme_renderer-29.0-py2.py3-none-any.whl (15 kB)
Requirement already satisfied: colorama>=0.4.3 in /usr/lib/python3/dist-packages (from twine->zeplyn) (0.4.3)
Collecting requests-toolbelt!=0.9.0,>=0.8.0
  Downloading requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
     |████████████████████████████████| 54 kB 8.9 MB/s
Collecting pkginfo>=1.4.2
  Downloading pkginfo-1.7.0-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: zipp>=0.5 in /usr/lib/python3/dist-packages (from importlib-metadata>=3.6->twine->zeplyn) (1.0.0)
Requirement already satisfied: secretstorage in /usr/lib/python3/dist-packages (from keyring>=15.1->twine->zeplyn) (2.3.1)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from readme-renderer>=21.0->twine->zeplyn) (1.14.0)
Collecting Pygments>=2.5.1
  Downloading Pygments-2.9.0-py3-none-any.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB 16.9 MB/s
Collecting bleach>=2.1.0
  Downloading bleach-3.3.0-py2.py3-none-any.whl (283 kB)
     |████████████████████████████████| 283 kB 17.1 MB/s
Collecting docutils>=0.13.1
  Downloading docutils-0.17.1-py2.py3-none-any.whl (575 kB)
     |████████████████████████████████| 575 kB 17.0 MB/s
Collecting packaging
  Downloading packaging-20.9-py2.py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 14.2 MB/s
Collecting webencodings
  Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 10.6 MB/s
Installing collected packages: pyparsing, webencodings, packaging, Pygments, docutils, bleach, tqdm, rfc3986, requests-toolbelt, readme-renderer, pkginfo, importlib-metadata, twine, zeplyn
  WARNING: The script pygmentize is installed in '/home/isaac/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script tqdm is installed in '/home/isaac/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pkginfo is installed in '/home/isaac/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script twine is installed in '/home/isaac/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed Pygments-2.9.0 bleach-3.3.0 docutils-0.17.1 importlib-metadata-4.5.0 packaging-20.9 pkginfo-1.7.0 pyparsing-2.4.7 readme-renderer-29.0 requests-toolbelt-0.9.1 rfc3986-1.5.0 tqdm-4.61.0 twine-3.4.1 webencodings-0.5.1 zeplyn-0.1.0
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.

**Comment by santoshlite** [comment]
2 questions:

Does it work?

Did you do it on the command prompt?

**Comment by Ixyk-Wolf** [comment]
No, and if WSL2 counts then I guess I did it on cmd.

**Comment by santoshlite** [comment]
Don't understand what's the problem, it works fine for me when I do the exact same thing...

**Comment by Ixyk-Wolf** [comment]
The problem is that the executable isn't there! You can't run the command! Does that make sense?

**Comment by santoshlite** [comment]
Yes, but I don't know why
